name: Test
on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    services:
      mongodb:
        image: mongo:4.4.6
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: APP-DATABASE
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install poetry
        run: pipx install poetry

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: install dependencies
        run: poetry install
      - name: Run the tests
        run: pytest -v
